### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by stryker313** [smix8/Godot_3D_Navigation_Jump_Links#1]
Hi! I used this plugin a couple of months back, however, it wasn't as modular as I hoped it to be. However, its got some really good ideas behind it, so I was hoping to use some aspects of it in my AI pathfinding, so I had a couple of questions

1. How does the AI evaluate when lets say using a latter is faster than using the stairs? I had trouble finding it in the code. You said you used weights and whatnot, but I was hoping you could help me understand this better. Is the AI taking the distance of the path into consideration, or is it based largely on a predetermined weight value?

2. What exactly is being "precalculated" to avoid extra costs? I was looking through build_navmesh_links(), but I didn't understand what calculations were at work. I was wondering if you could give a short abbreviated list of what's going on in that function.

3. Anything you recommend studying/looking at? Like anything you used to make this addon?

Thanks for taking the time! I'm surprised this plugin isn't actually used more often. Its extremely underrated for what it offers. Like when I found it, I was surprised that most of these ideas weren't already in the default godot.

**Comment by smix8** [comment]
Hey @stryker313,

1.) JumplinkNavigation._calc_jumplink_connection_cost() shows you how the cost for a single connection is calculated. It is the distance covered between the two jumplink nodes multiplied by the JumpLink timecost, later multiplied by the weight cost of the parent JumpLinkObject. Timecost is set on each JumpLink Node and weight is set on each parent JumpLinkObject Node. The runtime calculation for a path are done in JumpLinkNavigation.get_jumplink_path(). All the calculations assume an agent speed of 1. To make a fast moving agent prefer a jumplink over using normal land traveling while staying on the same navmesh island you reduce the timecost or the artifical weight value on the nodes.

2.) At scene start the script builds a graph of all the available navmesh islands connect by jumplinks. It calculates the shortest path from one navmesh island to all other navmesh islands. This paths are saved in a dictionary for resuse and when an agents wants to travel from one island to another it uses the already calculated paths from the dictionary. At runtime only the path from agent to first jumpnode and from last jumpnode to target are calculated. Godot default navigation travels through the navmesh graph from start to finish everytime you request a path which can be very costly with long path distances.

3.) I didn't use any source material for this addon apart from a python dijkstra example that I found at random on the internet that I adapted to GDScript.
Later I added some sources to the Godot proposal:
https://github.com/godotengine/godot-proposals/issues/2527

I am currently (slowly) reworking the addon for my own project though no public updates on the github repos for now. Only reworking for Godot 3.x cause Godot 4.x navigation is to messy rightnow.

**Comment by stryker313** [comment]
@smix8 Thanks! I'll definitely be bouncing around my own research and here, but this will be a big help. I've been experimenting recently with using "cheat" navigation meshes, whereby you simply generate several different navigations with varying inclines/areas with which the ai can go through, and using various functions to help the AI determine which navigation mesh it should be using to reach the player. I think combining what I've been using with some of the stuff you got here will yield awesome results! Thanks again!
