### ISSUE TITLE
Godot 3.5 Support

### ISSUE THREAD

**Issue by MichaelJBrune** [smix8/Godot_3D_Navigation_Jump_Links#3]
Hey,

I wanted to check in and see if there was support for 3.5 planned. I was looking at the 4.x branch and it seems like godot 3.5 is going to take a bit of effort to port to from either side. Likely easier to take the 4.x branch and remove the 4.x bits. Has there been any work towards this?

Thanks,
Michael Brune

**Comment by smix8** [comment]
@MJBrune 
Hello and sorry for the late response.

Yes, I am working on a new and improved version of the jumplink addon that works with the new NavigationServer in Godot 4.x that was now ported to Godot 3.x. Unfortunately there are a lot of issues currently with the new navigation implementation in Godot that slows down progress and the 3.x port is botched with a lot of issues and missing exposed functions required for this addon. I am currently waiting until official Godot navigation sorts out all the main issues.

**Comment by MichaelJBrune** [comment]
Hey, No worries, we all work on our own time. What are the issues that you've seen? Maybe I can try to make a pull request to the engine to fix or address these things. If I can get an idea of what's going on with how 3.5 broke the nav link behavior maybe I can work on solving the overall issue. From my limited time with it, it was seeming like there wasn't a good way to get the navmesh instance from the nav system anymore. Is this the case?

**Comment by smix8** [comment]
@MJBrune 
A few issues like missing exposed RID functions have been fixed.

One main issue is that the NavigationServer get_closest_point_owner() now returns Map RID's instead of References to SceneTree NavigationMeshInstances like before. Since Map's are already merged information of all NavigationMeshInstances the critical information for this addon which SceneTree Node contributed which part of the navmesh seems to be no longer available.

**Comment by MichaelJBrune** [comment]
Yeah, that's exactly what I ran into trying to port to 3.5 too. Is there any open issue with this on Godot's end? If not I'd be happy to get the ball rolling and perhaps even write the bits that are needed. Although it highly depends on the new system and if that information is even available anymore.

**Comment by smix8** [comment]
@MJBrune 
As far as I know there is no specific issue open yet.


The current order in Godot 4.x and Godot 3.x how the merged navmesh is created is like this:

`GodotNavigationServer::region_bake_navmesh(Ref<NavigationMesh> r_mesh, Node *p_node)`
-->Entry point with both references to meshresource and region node.

`NavigationMeshGenerator::bake(Ref<NavigationMesh> p_nav_mesh, Node *p_node)`
--> Starts the parse of the navigationmesh from the NavigationRegion Node NavigationMesh Resource.

This is als the point where the region node information is dropped and only the mesh resource is used.

`NavigationMeshGenerator::_build_recast_navigation_mesh()`
--> creates the final merged mesh result with the ReCast navigation module.

`NavigationMeshGenerator::_convert_detail_mesh_to_native_navigation_mesh(const rcPolyMeshDetail *p_detail_mesh, Ref<NavigationMesh> p_nav_mesh)`
--> This has still the Reference to the NavigationMesh but no longer to the Node in the SceneTree.

**Comment by smix8** [comment]
With https://github.com/godotengine/godot/pull/60661 merged among some other fixes the main obstacles for Godot 3.5 support are now removed.

I don't think I will be ready with a new addon version when Godot 3.5 is released but should follow soon after.

**Comment by smix8** [comment]
Fixed with 4c04cb555bbe71ab1dcc6d36a717b59e736355a3

**Comment by MichaelJBrune** [comment]
Wonderful work. I'm very excited for it
